name: BedWars1058-TeamSelector
author: andrei1058 Trystage4C01
version: ${project.version}
description: Team Selector Add-on for BedWars1058 Minigame.
website: https://andrei1058.dev
main: com.andrei1058.bedwars.teamselector.Main
softdepend: [BedWars1058]
api-version: '1.13'